#!/usr/bin/python
#
# Copyright 2020 Ian Cohn <cohnic@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#Factored for Python 3
"""Returns a spcified value given a supplied JSON string, schema, and path"""
from __future__ import absolute_import

import json

def get_json_schema(object):
#    #Process input variable, validate json
#    if isinstance(object, str):
#        try:
#            object = json.loads(object)
#            print("Valid JSON string submitted. Converting it now to an object..")
#        except:
#            print("Invalid JSON submitted.")
#            raise
#    elif isinstance(object, list) or isinstance(object, dict):
#        print("Valid JSON object submitted. Processing now..")
# Commented out to assume object input for now
